import { Injectable } from '@angular/core';
import { Observable, of } from 'rxjs';
import { delay, map } from 'rxjs/operators';
import { GeocodingResult, Location, PoiSearchResult, SearchMode } from '@trip-planner/types';
import { HttpClient, HttpParams } from '@angular/common/http';
import { environment } from 'apps/trip-frontend/src/environments/environment';

@Injectable({
  providedIn: 'root',
})
export class LocationSearchService {
  private readonly apiUrl = environment.backendApiUrl;

  constructor(private http: HttpClient) {}

  /**
   * Searches for locations by calling the appropriate backend endpoint based on the search mode.
   * @param query The search string entered by the user.
   * @param mode The search mode, either 'address' or 'place'.
   * @returns An Observable of an array of Location objects.
   */
  searchLocations(query: string, mode: SearchMode): Observable<Location[]> {
    if (mode === 'address') {
      return this.searchByAddress(query);
    } else {
      return this.searchByPlace(query);
    }
  }

  /**
   * Calls the forward geocoding endpoint to search for addresses.
   * @param query The address string.
   */
  private searchByAddress(query: string): Observable<Location[]> {
    const params = new HttpParams().set('search', query);
    const endpoint = `${this.apiUrl}/geocoding/forward`;

    return this.http
      .get<GeocodingResult[]>(endpoint, { params })
      .pipe(map(results => results.map(this.transformGeocodingResultToLocation)));
  }

  /**
   * Calls the POI search endpoint to search for places.
   * @param query The place name string.
   */
  private searchByPlace(query: string): Observable<Location[]> {
    const params = new HttpParams().set('search', query);
    const endpoint = `${this.apiUrl}/poi/poi-search`;

    return this.http
      .get<PoiSearchResult[]>(endpoint, { params })
      .pipe(map(results => results.map(this.transformPoiResultToLocation)));
  }

  /**
   * Transforms a backend GeocodingResult into the frontend Location model.
   * @param result A single result from the /geocoding/forward API.
   */
  private transformGeocodingResultToLocation(result: GeocodingResult): Location {
    return {
      // Use the providerId as the unique ID for tracking in the UI.
      id: result.providerId,
      // For a plain address, the name is often the full address itself.
      name: result.fullAddress || 'Unknown Address',
      description: null, // No description from geocoding
      latitude: result.latitude,
      longitude: result.longitude,
      address: result.fullAddress,
      city: result.city,
      state: result.region, // Map backend 'region' to frontend 'state' - maybe change this later
      country: result.country,
      postalCode: result.postalCode,
      apiSource: null,
      apiSourceId: result.providerId,
      category: null,
      public: false,
      // Timestamps currently not generated by backend.
      createdAt: new Date(),
      updatedAt: new Date(),
    };
  }

  private transformPoiResultToLocation(result: PoiSearchResult): Location {
    return {
      id: result.providerId,
      name: result.name,
      description: null, // No description from POI search
      latitude: result.latitude,
      longitude: result.longitude,
      address: result.fullAddress,
      city: result.city,
      state: result.region,
      country: result.country,
      postalCode: result.postalCode,
      apiSource: null,
      apiSourceId: result.providerId,
      category: null,
      public: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    };
  }
}
